spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grandia_db?useSSL=false
    username: grandia
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.example.com
    port: 587
    username: example@example.com
    password: secret
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true